package com.retroeditor.service.gameboy;

import java.util.List;

/**
 * Generador de código C para GBDK-2020 a partir de parámetros de audio y melodías con timeline de Game Boy.
 */
public class GameBoySoundCodeGenerator {

    public String generateSoundCode(String channel, int frequency, int volume, String dutyCycle, int durationMs, boolean includeConst) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Samaruc - Game Boy Audio Editor\n");
        if (includeConst) {
            sb.append("const ");
        }
        String symbol = channel.toLowerCase().replace(' ', '_').replace('1', '1').replace('2', '2');
        sb.append("unsigned char ").append(symbol).append("_sound_data[] = {\n");
        sb.append("    // Channel: ").append(channel).append("\n");
        sb.append("    // Freq: ").append(frequency).append("Hz, Vol: ").append(volume).append(", Duty: ").append(dutyCycle).append(", Duration: ").append(durationMs).append("ms\n");

        int dutyBits = 0x80; // 50%
        if ("12.5%".equals(dutyCycle)) dutyBits = 0x00;
        else if ("25%".equals(dutyCycle)) dutyBits = 0x40;
        else if ("75%".equals(dutyCycle)) dutyBits = 0xC0;

        int volBits = (volume & 0x0F) << 4;

        sb.append(String.format("    0x%02X, 0x%02X, 0x%02X, 0x%02X\n", dutyBits, volBits, 0, 0));
        sb.append("};\n\n");

        sb.append("void play_").append(symbol).append("_effect(void) {\n");
        sb.append("    NR52_REG = 0x80; // Turn sound on\n");
        sb.append("    NR50_REG = 0x77; // Master volume\n");
        sb.append("    NR51_REG = 0xFF; // Enable all channels\n");
        if (!channel.contains("Noise")) {
            sb.append(String.format("    NR11_REG = 0x%02X;\n", dutyBits));
            sb.append(String.format("    NR12_REG = 0x%02X;\n", volBits | 0x07));
            sb.append("    NR13_REG = 0x83;\n");
            sb.append("    NR14_REG = 0x86;\n");
        } else {
            sb.append("    NR43_REG = 0x11;\n");
            sb.append(String.format("    NR42_REG = 0x%02X;\n", volBits));
            sb.append("    NR44_REG = 0x80;\n");
        }
        sb.append("}\n");

        return sb.toString();
    }

    public String generateMelodyCode(String melodyName, List<GameBoyAudioPlayer.NoteStep> steps, boolean includeConst) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Samaruc - Game Boy Timeline Melody Composer\n");
        String safeName = sanitizeSymbol(melodyName);

        if (includeConst) {
            sb.append("const ");
        }
        sb.append("unsigned int ").append(safeName).append("_melody_freqs[] = {");
        for (int i = 0; i < steps.size(); i++) {
            sb.append(steps.get(i).getFrequency()).append(i < steps.size() - 1 ? ", " : "");
        }
        sb.append("};\n");

        if (includeConst) {
            sb.append("const ");
        }
        sb.append("unsigned int ").append(safeName).append("_melody_durs[] = {");
        for (int i = 0; i < steps.size(); i++) {
            sb.append(steps.get(i).getDurationMs()).append(i < steps.size() - 1 ? ", " : "");
        }
        sb.append("};\n");

        if (includeConst) {
            sb.append("const ");
        }
        sb.append("unsigned int ").append(safeName).append("_melody_starts[] = {");
        for (int i = 0; i < steps.size(); i++) {
            sb.append(steps.get(i).getStartTimeMs()).append(i < steps.size() - 1 ? ", " : "");
        }
        sb.append("};\n\n");

        sb.append("void play_").append(safeName).append("_melody(void) {\n");
        sb.append("    NR52_REG = 0x80; // Turn sound on\n");
        sb.append("    NR50_REG = 0x77; // Master volume\n");
        sb.append("    NR51_REG = 0xFF; // Enable all channels\n");
        sb.append("    unsigned int current_time = 0;\n");
        sb.append("    unsigned char i;\n");
        sb.append("    for (i = 0; i < ").append(steps.size()).append("; i++) {\n");
        sb.append("        unsigned int start = ").append(safeName).append("_melody_starts[i];\n");
        sb.append("        if (start > current_time) {\n");
        sb.append("            delay(start - current_time);\n");
        sb.append("            current_time = start;\n");
        sb.append("        }\n");
        sb.append("        unsigned int f = ").append(safeName).append("_melody_freqs[i];\n");
        sb.append("        unsigned int gb_freq = (f > 0) ? (2048 - (131072 / f)) : 0;\n");
        sb.append("        NR13_REG = (unsigned char)(gb_freq & 0xFF);\n");
        sb.append("        NR14_REG = (unsigned char)(0x80 | ((gb_freq >> 8) & 0x07));\n");
        sb.append("        NR11_REG = 0x80;\n");
        sb.append("        NR12_REG = 0xF0;\n");
        sb.append("        unsigned int dur = ").append(safeName).append("_melody_durs[i];\n");
        sb.append("        delay(dur);\n");
        sb.append("        current_time += dur;\n");
        sb.append("    }\n");
        sb.append("}\n");

        return sb.toString();
    }

    private String sanitizeSymbol(String name) {
        String raw = name != null ? name.trim() : "melody";
        return raw.replaceAll("[^A-Za-z0-9_]", "_");
    }
}
