package com.retroeditor.service.gameboy;

/**
 * Formateador para exportar tilemaps a archivos .h y .c para GBDK-2020.
 */
public class GameBoyTilemapFormatter {
    private static final int BYTES_PER_LINE = 16;

    /**
     * Genera el contenido del archivo .h (header).
     */
    public String generateHeaderFile(String baseName) {
        String guardName = sanitizeSymbol(baseName).toUpperCase() + "_H";
        String mapSymbol = sanitizeSymbol(baseName) + "_map_data";
        String tileSymbol = sanitizeSymbol(baseName) + "_tile_data";

        StringBuilder sb = new StringBuilder();
        sb.append("#ifndef ").append(guardName).append("\n");
        sb.append("#define ").append(guardName).append("\n\n");

        sb.append("extern const unsigned char ").append(mapSymbol).append("[];\n");
        sb.append("extern const unsigned char ").append(tileSymbol).append("[];\n\n");

        sb.append("#endif // ").append(guardName).append("\n");

        return sb.toString();
    }

    /**
     * Genera el contenido del archivo .c (source) con los datos.
     */
    public String generateSourceFile(String baseName, GameBoyTilemapResult result) {
        StringBuilder sb = new StringBuilder();

        String mapSymbol = sanitizeSymbol(baseName) + "_map_data";
        String tileSymbol = sanitizeSymbol(baseName) + "_tile_data";

        // Defines con tamaños
        sb.append("// Generated by Samaruc - Game Boy Tilemap Exporter\n\n");
        sb.append("#define ").append(sanitizeSymbol(baseName).toUpperCase())
            .append("_MAP_WIDTH  0x").append(String.format("%02X", result.getMapWidth())).append("  // ").append(result.getMapWidth()).append(" tiles\n");
        sb.append("#define ").append(sanitizeSymbol(baseName).toUpperCase())
            .append("_MAP_HEIGHT 0x").append(String.format("%02X", result.getMapHeight())).append("  // ").append(result.getMapHeight()).append(" tiles\n");
        sb.append("#define ").append(sanitizeSymbol(baseName).toUpperCase())
            .append("_MAP_SIZE   0x").append(String.format("%04X", result.getMapDataSize())).append("  // ").append(result.getMapDataSize()).append(" bytes\n");
        sb.append("#define ").append(sanitizeSymbol(baseName).toUpperCase())
            .append("_TILE_COUNT 0x").append(String.format("%02X", result.getTileCount())).append("  // ").append(result.getTileCount()).append(" unique tiles\n\n");

        // Map data
        sb.append("const unsigned char ").append(mapSymbol).append("[] = {\n");
        formatByteArray(sb, result.getMapData());
        sb.append("};\n\n");

        // Tile data
        sb.append("const unsigned char ").append(tileSymbol).append("[] = {\n");
        formatByteArray(sb, result.getTileData());
        sb.append("};\n");

        return sb.toString();
    }

    /**
     * Formatea un array de bytes en código C.
     */
    private void formatByteArray(StringBuilder sb, byte[] data) {
        for (int i = 0; i < data.length; i++) {
            if (i > 0) {
                sb.append(",");
            }

            if (i % BYTES_PER_LINE == 0) {
                sb.append("\n    ");
            } else {
                sb.append(" ");
            }

            sb.append(String.format("0x%02X", data[i] & 0xFF));
        }
        sb.append("\n");
    }

    /**
     * Sanitiza un nombre de símbolo C.
     */
    private String sanitizeSymbol(String name) {
        if (name == null || name.trim().isEmpty()) {
            return "tilemap";
        }

        // Remover extensión .png si existe
        String base = name;
        if (base.endsWith(".png") || base.endsWith(".PNG")) {
            base = base.substring(0, base.length() - 4);
        }

        StringBuilder sb = new StringBuilder();
        for (char c : base.toCharArray()) {
            if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_') {
                sb.append(c);
            } else {
                sb.append('_');
            }
        }

        // No puede empezar con número
        if (!sb.isEmpty() && sb.charAt(0) >= '0' && sb.charAt(0) <= '9') {
            sb.insert(0, '_');
        }

        return sb.toString();
    }
}
