package com.retroeditor.service;

/**
 * Generador de código C para tiles de Game Boy en formato 2bpp.
 */
public class GameBoyTileCodeGenerator {

    public static final int TILE_SIZE = 8;

    /**
     * Convierte un tile 8x8 de valores [0..3] al formato 2bpp de Game Boy (16 bytes).
     *
     * @param pixels matriz de 8x8, donde cada valor representa un color de 2 bits.
     * @return array de 16 bytes en orden por filas (low, high).
     */
    public byte[] to2bppBytes(int[][] pixels) {
        validatePixels(pixels);

        byte[] output = new byte[16];
        int offset = 0;

        for (int row = 0; row < TILE_SIZE; row++) {
            int low = 0;
            int high = 0;
            for (int col = 0; col < TILE_SIZE; col++) {
                int value = pixels[row][col] & 0x03;
                int bit = 7 - col;
                if ((value & 0x01) != 0) low |= (1 << bit);
                if ((value & 0x02) != 0) high |= (1 << bit);
            }
            output[offset++] = (byte) low;
            output[offset++] = (byte) high;
        }

        return output;
    }

    /**
     * Genera el código C listo para pegar/exportar con opciones.
     *
     * @param pixels matriz de 8x8 con valores [0..3].
     * @param symbolName nombre de símbolo C para el array.
     * @param includeConst si se debe incluir el modificador 'const'.
     * @param includeDefines si se deben incluir #defines para el tamaño.
     * @return texto de código C.
     */
    public String generateTileCode(int[][] pixels, String symbolName, boolean includeConst, boolean includeDefines) {
        byte[] bytes = to2bppBytes(pixels);
        String safeSymbol = sanitizeSymbol(symbolName);

        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Samaruc Tile Editor (Game Boy 2bpp)\n");

        if (includeDefines) {
            sb.append("#define ").append(safeSymbol.toUpperCase()).append("_WIDTH 8\n");
            sb.append("#define ").append(safeSymbol.toUpperCase()).append("_HEIGHT 8\n");
            sb.append("#define ").append(safeSymbol.toUpperCase()).append("_TILE_COUNT 1\n\n");
        }

        if (includeConst) {
            sb.append("const ");
        }
        sb.append("unsigned char ").append(safeSymbol).append("[] = {\n");

        for (int i = 0; i < bytes.length; i += 2) {
            int row = i / 2;
            sb.append(String.format("    0x%02X, 0x%02X", bytes[i] & 0xFF, bytes[i + 1] & 0xFF));
            if (i + 2 < bytes.length) sb.append(",");
            sb.append(" // row ").append(row).append("\n");
        }

        sb.append("};\n");
        return sb.toString();
    }

    /**
     * Método de compatibilidad para llamadas antiguas.
     */
    public String generateTileCode(int[][] pixels, String symbolName) {
        return generateTileCode(pixels, symbolName, true, false);
    }

    private void validatePixels(int[][] pixels) {
        if (pixels == null || pixels.length != TILE_SIZE) {
            throw new IllegalArgumentException("La matriz de pixels debe ser 8x8.");
        }
        for (int row = 0; row < TILE_SIZE; row++) {
            if (pixels[row] == null || pixels[row].length != TILE_SIZE) {
                throw new IllegalArgumentException("La matriz de pixels debe ser 8x8.");
            }
            for (int col = 0; col < TILE_SIZE; col++) {
                int value = pixels[row][col];
                if (value < 0 || value > 3) {
                    throw new IllegalArgumentException("Cada pixel debe estar en el rango [0..3].");
                }
            }
        }
    }

    private String sanitizeSymbol(String symbolName) {
        String raw = symbolName != null ? symbolName.trim() : "";
        if (raw.isEmpty()) raw = "tile_data";

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            boolean valid = (c >= 'a' && c <= 'z')
                || (c >= 'A' && c <= 'Z')
                || (c >= '0' && c <= '9')
                || c == '_';
            sb.append(valid ? c : '_');
        }

        if (sb.length() == 0) return "tile_data";
        char first = sb.charAt(0);
        if ((first >= '0' && first <= '9')) {
            sb.insert(0, '_');
        }
        return sb.toString();
    }
}

