package com.retroeditor.service;

/**
 * Generador de código C para tiles de Game Boy en formato 2bpp.
 */
public class GameBoyTileCodeGenerator {

    public static final int TILE_SIZE = 8;

    /**
     * Convierte una matriz de píxeles (dimensiones múltiplos de 8, ej. 8x8, 8x16, 16x16)
     * al formato 2bpp de Game Boy en orden de tiles por filas (16 bytes por tile 8x8).
     *
     * @param pixels matriz de [height][width], donde cada valor representa un color de 2 bits.
     * @return array de bytes en formato 2bpp.
     */
    public byte[] to2bppBytes(int[][] pixels) {
        validatePixels(pixels);

        int height = pixels.length;
        int width = pixels[0].length;
        int tileRows = height / 8;
        int tileCols = width / 8;

        byte[] output = new byte[tileRows * tileCols * 16];
        int offset = 0;

        for (int tr = 0; tr < tileRows; tr++) {
            for (int tc = 0; tc < tileCols; tc++) {
                for (int r = 0; r < 8; r++) {
                    int row = tr * 8 + r;
                    int low = 0;
                    int high = 0;
                    for (int c = 0; c < 8; c++) {
                        int col = tc * 8 + c;
                        int value = pixels[row][col] & 0x03;
                        int bit = 7 - c;
                        if ((value & 0x01) != 0) low |= (1 << bit);
                        if ((value & 0x02) != 0) high |= (1 << bit);
                    }
                    output[offset++] = (byte) low;
                    output[offset++] = (byte) high;
                }
            }
        }

        return output;
    }

    /**
     * Genera el código C listo para pegar/exportar con opciones.
     *
     * @param pixels matriz con dimensiones múltiplo de 8 y valores [0..3].
     * @param symbolName nombre de símbolo C para el array.
     * @param includeConst si se debe incluir el modificador 'const'.
     * @param includeDefines si se deben incluir #defines para ancho, alto y número de tiles.
     * @return texto de código C.
     */
    public String generateTileCode(int[][] pixels, String symbolName, boolean includeConst, boolean includeDefines) {
        validatePixels(pixels);
        byte[] bytes = to2bppBytes(pixels);
        String safeSymbol = sanitizeSymbol(symbolName);
        int height = pixels.length;
        int width = pixels[0].length;
        int tileCount = (width / 8) * (height / 8);

        StringBuilder sb = new StringBuilder();
        sb.append("// Generated by Samaruc Tile Editor (Game Boy 2bpp)\n");

        if (includeDefines) {
            sb.append("#define ").append(safeSymbol.toUpperCase()).append("_WIDTH ").append(width).append("\n");
            sb.append("#define ").append(safeSymbol.toUpperCase()).append("_HEIGHT ").append(height).append("\n");
            sb.append("#define ").append(safeSymbol.toUpperCase()).append("_TILE_COUNT ").append(tileCount).append("\n\n");
        }

        if (includeConst) {
            sb.append("const ");
        }
        sb.append("unsigned char ").append(safeSymbol).append("[] = {\n");

        for (int i = 0; i < bytes.length; i += 2) {
            int tileIndex = i / 32;
            int rowInTile = (i / 2) % 8;
            sb.append(String.format("    0x%02X, 0x%02X", bytes[i] & 0xFF, bytes[i + 1] & 0xFF));
            if (i + 2 < bytes.length) sb.append(",");
            sb.append(" // tile ").append(tileIndex).append(", row ").append(rowInTile).append("\n");
        }

        sb.append("};\n");
        return sb.toString();
    }

    /**
     * Método de compatibilidad para llamadas antiguas.
     */
    public String generateTileCode(int[][] pixels, String symbolName) {
        return generateTileCode(pixels, symbolName, true, false);
    }

    private void validatePixels(int[][] pixels) {
        if (pixels == null || pixels.length == 0 || pixels.length % 8 != 0) {
            throw new IllegalArgumentException("La altura de la matriz de pixels debe ser múltiplo de 8.");
        }
        int height = pixels.length;
        int width = pixels[0].length;
        if (width == 0 || width % 8 != 0) {
            throw new IllegalArgumentException("El ancho de la matriz de pixels debe ser múltiplo de 8.");
        }
        for (int row = 0; row < height; row++) {
            if (pixels[row] == null || pixels[row].length != width) {
                throw new IllegalArgumentException("Todas las filas deben tener el mismo ancho.");
            }
            for (int col = 0; col < width; col++) {
                int value = pixels[row][col];
                if (value < 0 || value > 3) {
                    throw new IllegalArgumentException("Cada pixel debe estar en el rango [0..3].");
                }
            }
        }
    }

    private String sanitizeSymbol(String symbolName) {
        String raw = symbolName != null ? symbolName.trim() : "";
        if (raw.isEmpty()) raw = "tile_data";

        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < raw.length(); i++) {
            char c = raw.charAt(i);
            boolean valid = (c >= 'a' && c <= 'z')
                || (c >= 'A' && c <= 'Z')
                || (c >= '0' && c <= '9')
                || c == '_';
            sb.append(valid ? c : '_');
        }

        if (sb.length() == 0) return "tile_data";
        char first = sb.charAt(0);
        if ((first >= '0' && first <= '9')) {
            sb.insert(0, '_');
        }
        return sb.toString();
    }
}

